import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, CircleDashed, Github, LockKeyhole, Rocket, ShieldCheck, Sparkles } from "lucide-react";

export const metadata: Metadata = { title: "Beta readiness" };
const ready = ["Core review experience", "Responsive design system", "Structured demo critique", "Improvement and progress previews", "Privacy-first local data controls"];
const pending = ["Live vision model", "Accounts and private storage", "Persistent database history", "Production monitoring and rate limits", "Legal and accessibility review"];

export default function BetaPage() { return <div className="beta-page"><header className="simple-header beta-nav"><Link href="/" className="wordmark"><span className="wordmark-mark">D</span>DinoDesign</Link><nav><Link href="/pricing">Pricing preview</Link><Link className="button button-small" href="/review/new">Try the demo <ArrowRight /></Link></nav></header><main><section className="beta-hero"><div><p className="eyebrow light"><Rocket /> Launch readiness</p><h1>Built in the<br /><span>open.</span></h1><p>DinoDesign is a verified product demo, not a live AI service yet. Explore the full experience now and follow the remaining work toward a private alpha.</p><div><Link className="button button-lime button-large" href="/review/new">Try the product demo <Sparkles /></Link><a className="button-quiet beta-link" href="https://github.com/painjanevivek/DinoDesign" target="_blank" rel="noreferrer">View the repository <Github /></a></div></div><div className="launch-meter"><span className="mono-label">PRIVATE ALPHA READINESS</span><strong>13<small>/13</small></strong><p>Product phases planned and represented</p><div><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /></div><small>External infrastructure gates remain separate.</small></div></section><section className="readiness-grid section-pad"><article><header><Check /> <div><span className="mono-label">READY TO EVALUATE</span><h2>Product experience</h2></div></header>{ready.map((item) => <p key={item}><Check />{item}</p>)}</article><article><header><CircleDashed /> <div><span className="mono-label">REQUIRED BEFORE ALPHA</span><h2>Live infrastructure</h2></div></header>{pending.map((item) => <p key={item}><CircleDashed />{item}</p>)}</article></section><section className="alpha-principles"><div><p className="eyebrow light"><ShieldCheck /> Trust before growth</p><h2>No launch theater.</h2><p>The demo says when feedback is simulated. The community says when posting is unavailable. Pricing says when checkout does not exist. That honesty remains part of the product when the real services arrive.</p></div><div><LockKeyhole /><h3>Private alpha first</h3><p>A small invited cohort will validate feedback usefulness, mode safety, upload recovery, privacy, and deletion before broad promotion.</p><Sparkles /><h3>Quality before categories</h3><p>The core rubric must be reliably useful across the first categories before more formats or generation features are opened.</p></div></section><section className="beta-cta"><p className="eyebrow">Explore what is ready</p><h2>Bring one design.<br /><span>Leave with direction.</span></h2><Link className="button button-dark button-large" href="/review/new">Start a demo critique <ArrowRight /></Link></section></main></div>; }
