import type { Metadata } from "next";
import "@/app/route-styles.css";
import Link from "next/link";
import { ArrowRight, Github, LockKeyhole, Rocket, ShieldCheck, Sparkles } from "lucide-react";
import { HeaderAuthLinks } from "@/features/auth/auth-nav";
import { ReadinessDiagnostics } from "./readiness-diagnostics";

export const metadata: Metadata = { title: "Beta readiness" };

export default function BetaPage() { return <div className="beta-page"><header className="simple-header beta-nav"><Link href="/" className="wordmark"><span className="wordmark-mark">I</span>IroGuide</Link><nav><Link href="/pricing">Pricing preview</Link><HeaderAuthLinks includeDashboard={false} /></nav></header><main><section className="beta-hero diagnostics-hero"><div><p className="eyebrow light"><Rocket /> Launch readiness</p><h1>Deployment<br /><span>diagnostics.</span></h1><p>Check the live wiring that makes IroGuide useful in staging and production: Firebase account storage, matching project configuration, and the live vision review provider that analyzes uploaded pixels.</p><div><Link className="button button-lime button-large" href="/auth?mode=sign-up">Run a signed-in review <Sparkles /></Link><a className="button-quiet beta-link" href="https://github.com/painjanevivek/IroGuide" target="_blank" rel="noreferrer">View the repository <Github /></a></div></div><div className="diagnostics-orb"><span className="mono-label">LIVE SOURCE</span><strong>/api</strong><p>Readiness is pulled from the deployed server, not a static launch checklist.</p><small>/api/readiness</small></div></section><ReadinessDiagnostics /><section className="alpha-principles"><div><p className="eyebrow light"><ShieldCheck /> Trust before growth</p><h2>No launch theater.</h2><p>The page now shows whether Firebase Admin, client project alignment, and live review credentials are actually configured in the running environment.</p></div><div><LockKeyhole /><h3>Fix staging first</h3><p>Use the failing rows as the shortest path to restore sign-in verification, private storage, and review persistence before inviting testers.</p><Sparkles /><h3>Then prove the loop</h3><p>Once the checks pass, run a signed-in upload review and confirm the result uses live vision critique instead of local demo mode.</p></div></section><section className="beta-cta"><p className="eyebrow">Explore what is ready</p><h2>Bring one design.<br /><span>Leave with direction.</span></h2><Link className="button button-dark button-large" href="/auth?mode=sign-up">Create account <ArrowRight /></Link></section></main></div>; }
