export const siteConfig = {
  name: "IroGuide",
  url: process.env.NEXT_PUBLIC_SITE_URL?.trim().replace(/\/+$/, "") || "https://iroguide.com",
  title: "IroGuide - AI Design Critique and Creative Feedback",
  description:
    "IroGuide is the official AI design critique workspace for creative feedback, project reviews, portfolio refinement, and clearer next steps.",
  shortDescription:
    "Professional, contextual AI critique that tells you what works, what does not, and what to fix next.",
  keywords: [
    "IroGuide",
    "IroGuide official",
    "AI design critique",
    "design feedback",
    "creative feedback",
    "portfolio review",
    "design review tool",
    "UI critique",
    "logo critique",
    "poster critique",
  ],
  logoPath: "/brand/iroguide-logo.png",
  creator: "IroGuide",
  repositoryUrl: "https://github.com/painjanevivek/IroGuide",
  contactUrl: "/contact",
  supportEmail: "support@iroguide.com",
  navigation: [
    { label: "How it works", href: "/#how-it-works" },
    { label: "Modes", href: "/#modes" },
    { label: "Example review", href: "/#example" },
  ],
  footerNavigation: [
    { label: "About", href: "/about" },
    { label: "Projects", href: "/projects" },
    { label: "Docs", href: "/docs" },
    { label: "Contact", href: "/contact" },
    { label: "Bug report", href: "/contact#bug-report" },
    { label: "Pricing", href: "/pricing" },
    { label: "Community", href: "/community" },
    { label: "Beta", href: "/beta" },
    { label: "Privacy", href: "/privacy" },
    { label: "Terms", href: "/terms" },
  ],
} as const;
