"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _iroguide_site_shell from './iroguide-site-shell.bones.json'

configureBoneyard({"color":"rgba(9, 9, 15, 0.09)","darkColor":"rgba(255, 255, 255, 0.12)","animate":"shimmer","shimmerColor":"rgba(255, 255, 255, 0.45)","darkShimmerColor":"rgba(255, 255, 255, 0.18)","speed":"1.65s","shimmerAngle":108,"transition":260})

registerBones({
  "iroguide-site-shell": _iroguide_site_shell,
})
